coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        if_ci_failed: ignore #success, failure, error, ignore
        informational: false
        only_pulls: false


fixes:
- "ballerina/udp/*/::udp-ballerina/"

ignore:
- "**/test"
